---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  labels:
    name: myapp
spec:
  replicas: 2
  selector: 
    matchLabels:
      name: myapp 
  template:
    metadata:
      labels:
        name: myapp
    spec:
      containers:
      - name: myapp
        image: srinath246/myapp:1.1
        ports:
        - containerPort: 80
